from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QSpacerItem, QSizePolicy, QLineEdit, QLabel
from PyQt5.QtGui import QFont

# UI
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 870)
        Form.setWindowTitle("CvDl_Hw1_P66134145")
        
        self.centralwidget = QtWidgets.QWidget(Form)
        #self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 30, 250, 300))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(15, 30, 220, 250))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.button_1_1 = QtWidgets.QPushButton("Load Folder", self.verticalLayoutWidget)
        self.filePathLabel_1 = QLabel("", self.verticalLayoutWidget)
        self.button_1_2 = QtWidgets.QPushButton("Load Image_L", self.verticalLayoutWidget)
        self.filePathLabel_2 = QLabel("", self.verticalLayoutWidget)
        self.button_1_3 = QtWidgets.QPushButton("Load Image_R", self.verticalLayoutWidget)
        self.filePathLabel_3 = QLabel("", self.verticalLayoutWidget)
        self.verticalLayout.addWidget(self.button_1_1)
        self.verticalLayout.addWidget(self.filePathLabel_1)
        self.verticalLayout.addWidget(self.button_1_2)
        self.verticalLayout.addWidget(self.filePathLabel_2)
        self.verticalLayout.addWidget(self.button_1_3)
        self.verticalLayout.addWidget(self.filePathLabel_3)
        self.label = QtWidgets.QLabel("Load Image", self.frame)
        #self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(10, 5, 100, 20))
        font = QFont()      #Bold
        font.setBold(True)
        self.label.setFont(font)
        #sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        #sizePolicy.setHorizontalStretch(0)
        #sizePolicy.setVerticalStretch(0)
        #sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        #self.label.setSizePolicy(sizePolicy)
        
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(310, 30, 300, 390))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 260, 350))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.button_2_1 = QtWidgets.QPushButton("1.1 Find Corners", self.verticalLayoutWidget_2)
        self.button_2_2 = QtWidgets.QPushButton("1.2 Find Intrinsic", self.verticalLayoutWidget_2)
        
        self.frame_2_1 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_2_1.setGeometry(QtCore.QRect(5, 115, 246, 120))
        self.frame_2_1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_2_3 = QtWidgets.QPushButton("1.3 Find Extrinsic", self.frame_2_1)
        self.button_2_3.setGeometry(QtCore.QRect(50, 70, 150, 40))
        self.comboBox = QtWidgets.QComboBox(self.frame_2_1)
        self.comboBox.setGeometry(QtCore.QRect(50, 20, 150, 40))
        for i in range(1, 16):  # add item from 1 to 15
            self.comboBox.addItem(str(i))
        
        self.button_2_4 = QtWidgets.QPushButton("1.4 Find Distortion", self.verticalLayoutWidget_2)
        self.button_2_5 = QtWidgets.QPushButton("1.5 Show Result", self.verticalLayoutWidget_2)
        self.verticalLayout_2.addWidget(self.button_2_1)
        self.verticalLayout_2.addWidget(self.button_2_2)
        spacer = QSpacerItem(0, 140, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacer)
        self.verticalLayout_2.addWidget(self.button_2_4)
        self.verticalLayout_2.addWidget(self.button_2_5)
        self.label_2 = QtWidgets.QLabel("1.Calibration", self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 5, 150, 20))
        self.label_2.setFont(font)
        
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(650, 30, 300, 390))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 260, 350))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QtWidgets.QLabel("2. Augmented Reality", self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(10, 5, 150, 20))
        self.label_3.setFont(font)
        self.lineEdit = QLineEdit(self.verticalLayoutWidget_3)
        self.button_3_1 = QtWidgets.QPushButton("2.1 Show Words on Board", self.verticalLayoutWidget_3)
        self.button_3_2 = QtWidgets.QPushButton("2.2 Show Words Vertically", self.verticalLayoutWidget_3)
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_3.addWidget(self.button_3_1)
        self.verticalLayout_3.addWidget(self.button_3_2)
        
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(310, 450, 300, 390))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 30, 260, 350))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_4 = QtWidgets.QLabel("3. Stereo Disparity Map", self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(10, 5, 150, 20))
        self.label_4.setFont(font)
        self.button_4 = QtWidgets.QPushButton("3.1 Stereo Disparity Map", self.verticalLayoutWidget_4)
        self.verticalLayout_4.addWidget(self.button_4)
        
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(650, 450, 300, 390))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame_5)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 30, 260, 350))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QtWidgets.QLabel("4. SIFT", self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(10, 5, 150, 20))
        self.label_5.setFont(font)
        self.button_5_1 = QtWidgets.QPushButton("4.1 SIFT Keypoints", self.verticalLayoutWidget_5)
        self.button_5_2 = QtWidgets.QPushButton("4.2 Matched Keypoints", self.verticalLayoutWidget_5)
        self.verticalLayout_5.addWidget(self.button_5_1)
        self.verticalLayout_5.addWidget(self.button_5_2)